[[virtual_desktops]]
name = "1"
workspaces = [{ layout = "Columns" }, { layout = "Monocle" }]

[[virtual_desktops]]
name = "2"
workspaces = [{ layout = "Monocle" }, { layout = "Monocle" }]

[[virtual_desktops]]
name = "3"
workspaces = [{ layout = "Monocle" }, { layout = "Monocle" }]

[[virtual_desktops]]
name = "4"
workspaces = [{ layout = "Monocle" }, { layout = "Monocle" }]
