name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        feature: [windows10, windows11]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --no-default-features --features ${{ matrix.feature }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tilosrv-${{ matrix.feature }}
        path: |
          target/release/tilosrv.exe
          target/release/tiloctl.exe
