name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-win10:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --no-default-features --features windows10
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FancyTWM-win10
        path: target/release/FancyTWM.exe

  build-win11:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --no-default-features --features windows11
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FancyTWM-win11
        path: target/release/FancyTWM.exe
